### ISSUE TITLE
Handle MODIS  MOD09 files -  Atmospherically Corrected Surface Reflectance 5-Min L2 Swath 250m, 500m, 1km

### ISSUE THREAD

**Issue by NiklasPhabian** [SpatioTemporal/STAREmaster#42]
MOD09/MYD09 files contain MODIS level 2 surface reflectance data at 3 resolutions for Terra (MOD) and Aqua (MYD).

Granule size is about 350 MB. 

Geolocation is given only at the coarsest, 1km, resolution. Geolocation for 500m and 250m need to be interpolated. 

Spatial Resolution: 
250m (bands 1-2)
500m (bands 3-7)
1000m (bands 8-36)

The individual SDS resolution is clearly distinguishable from the SDS name prefix. Exceptions are the surface temperature bands 20, 31, 32, which are at 1km resolution.

Note that these files are part of our golden set ([on schiss](http://schiss.eri.ucsb.edu:8888/opendap/golden_set/contents.html) as defined by e.g. [this ladsweb query](https://ladsweb.modaps.eosdis.nasa.gov/search/order/4/MOD09--6,VNP09--5000/2020-02-27..2020-03-03/DB/-119.8,37.8,-118.6,36.9).)

The entire mission data can be found on ladsweb:
https://ladsweb.modaps.eosdis.nasa.gov/archive/allData/6/MOD09/
https://ladsweb.modaps.eosdis.nasa.gov/archive/allData/6/MYD09/

![image](https://user-images.githubusercontent.com/6323307/90960821-b90cfa80-e47a-11ea-916d-dc555142e761.png)

All relevant MOD09 links at ladsweb:
https://ladsweb.modaps.eosdis.nasa.gov/missions-and-measurements/products/MOD09/

MODIS Instrument / Bands info:
https://ladsweb.modaps.eosdis.nasa.gov/missions-and-measurements/modis/

**Comment by NiklasPhabian** [comment]
It might be worthwhile to forego the level2 products and rather only do a sidecar for the geolocationMOD03/MYD03 products. The lat/lon SDS of MOD09 is merely a replication of this data.

https://ladsweb.modaps.eosdis.nasa.gov/missions-and-measurements/products/MOD03

https://ladsweb.modaps.eosdis.nasa.gov/missions-and-measurements/products/MYD03

**Comment by michaelleerilee** [comment]
I believe for some of these datasets the higher resolution interpolated geolocations may be available in separate geolocation files. Sometimes it's not so easy to find a reference to these separate files.

**Comment by captainkirk99** [comment]
The MOD09 files are currently supported by STAREmaster, but this is not well documented. I will take a round of documentation this morning to get it caught up.

I looked into the resolution issue for a bit and unfortunately the higher resolutions are not included in the MOD03 files. I contacted the MODIS support people about this and this is what they had to say:

> Since the MODIS geolocation is estimated at 1km only so it is provided for 1km datasets only. The best way to use the 1m geolocation will be to co-locate each 500m/250m observations within the corresponding 1km pixel and then use the corresponding 1km geolocation.

So in the MOD09 files, we have three resolutions of data, but lat/lons only for the lowest resolution. What STAREmaster does, as suggested by James, is provide three sets of STARE indicies, one for each resolution. The higher resolution ones are simply binned. That is, 4 of the 250m observations share the 1 STARE index that applies at 1 km resolution. We also discussed interpolation, but James thought binning would be more correct. (And the MODIS support team suggest the same thing, see above.)

The MOD09 was chosen for STAREmaster because it allowed me to confront the problems of multiple resolutions in one file, something we knew we would have to confront. I wanted to ensure that the sidecar file has the capability of supporting multiple resolutions on one data file.
