### ISSUE TITLE
confusion about readme

### ISSUE THREAD

**Issue by NiklasPhabian** [SpatioTemporal/STAREmaster#89]
to clarify, while building hdfeos and hdf4 we set the prefix to /usr/local/hdfeos_fPIC and /usr/local/hdf-4.2.15_fPIC

Then, when building STAREmaster, the readme states to set cpp flags to /usr/local/hdfeos/ and /usr/local/hdf-4.2.15/ (not _fPIC). 

For someone who has no idea what is going on, this is confusing.

Also, the github actions installs netcdf-bin and libnetcdf-dev from the Ubuntu (18.04) repositories. This appears to replace the necessity to build netcdf from source? Might be worth mentioning. 

The github actions does not seem to find hdf5 (./configure barfs). It also does not seem the case that the github actions are installing or building hdf5. Is this meant to be the case? Same thing happens on my system even though I have libhdf5-dev installed from Ubuntu sources. On that point, when attempting to build netcdf-c, its configure script also tells me that it cannot find hdf5 library

configure: error: Can't find or link to the hdf5 library. Use --disable-netcdf-4, or see config.log for errors.

Which in itself is a confusing statement.

Semi-unrelated, what confuses me here is that when building hdf5 from source, the default installation does not seem to copy the libs and headrs to /usr/lib or /usr/local/lib but to somewhere in the build directory; ofc, can set the prefix, but just yet another thing to remember non-default options.

I really just want to use STAREmaster ... with those shenanigans; maybe worthwhile to ship precompiled builds?

**Comment by NiklasPhabian** [comment]
also, the readme help:

STARE spatial create sidecar file. 
Usage: createSidecarFile [options] [filename]} 
Examples:
  createSidecarFile data.nc
  createSidecarFile data.h5

Probably can drop the trailing curly bracket and change the filename to a non-optional argument (remove the brackets).

**Comment by captainkirk99** [comment]
@NiklasPhabian yes, when building, you must point CPPFLAGS/LDFLAGS to wherever you have installed HDF4 and hdfeos using -fPIC. I have cleaned up the README to more clearly reflect this.

The HDF4 and hdfeos builds are indeed annoying. They are quite old and were put together before some of the modern tools and conventions we use today became common. And there is no chance they will be updated, so we must just live with it. ;-)

NetCDF may be installed from Ubuntu or many other places. Any reasonably recent version of netCDF will do.

When building netCDF, if it can't find HDF5, it can't build netCDF-4. That is, only classic netCDF can be built, and that is supported with the --disable-netcdf-4 option. If you look for this error in the file called config.log you will see exactly why the compiler is not linking to HDF5. You may have to set CPPFLAGS/LDFLAGS. If you want help building netCDF attach the config.log and the full output of configure and make.

I'm not sure about what you are saying about HDF5. I install it frequently and I believe the default install location is /usr/local, as is autoconf custom. Of course the --prefix argument overrides this. What may be annoying you is that /usr/local/lib is usually not in your default LD_LIBRARY_PATH, and it should be.

Building is a challenge because of HDF4 and hdfeos. Otherwise, any recent netCDF will work, and that's easy to get. 

We have an issue for a binary install, so that is coming (see #37).
